<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>6b5e5abd-9047-4786-8bb6-6f85fd36d309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1_1_0_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f3814a74-4576-455b-8fed-9214ca7651f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>33657831-84ab-4b6a-a9ae-45cabe302750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_1_0_0&quot;)/i[@class=&quot;icon-trash&quot;]</value>
      <webElementGuid>4d593b6b-6153-491a-8c8c-a09e05c07538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1_1_0_0']/i</value>
      <webElementGuid>8e64005c-e680-4e17-b32d-7907cb00f3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a/i</value>
      <webElementGuid>34e080a1-2ec9-4fe3-a9c3-24217f366ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
