<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Blouse</name>
   <tag></tag>
   <elementGuidId>a255d58d-d5d6-4c56-ba1e-01c669a664e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='center_column']/ul/li/div/div[2]/h5/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.right-block > h5 > a.product-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d032139a-0dd7-4047-a401-894d66d0799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>31955370-578f-408d-a43c-ab18a5387bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://automationpractice.com/index.php?id_product=2&amp;controller=product&amp;search_query=Blouse&amp;results=1</value>
      <webElementGuid>311e9c7d-f6fc-46e4-b5b3-906116d8aaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Blouse</value>
      <webElementGuid>7f594eb2-4373-4066-9992-6d2176177c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>a82bf4d8-5281-4c20-8b1b-b9be4a28dcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Blouse
						</value>
      <webElementGuid>54b15e79-9993-4074-9f28-f0c911a2e227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center_column&quot;)/ul[@class=&quot;product_list grid row&quot;]/li[@class=&quot;ajax_block_product col-xs-12 col-sm-6 col-md-4 first-in-line last-line first-item-of-tablet-line first-item-of-mobile-line last-mobile-line hovered&quot;]/div[@class=&quot;product-container&quot;]/div[@class=&quot;right-block&quot;]/h5[1]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>8fae8d7e-6db2-4d18-b732-5ec00d95a458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center_column']/ul/li/div/div[2]/h5/a</value>
      <webElementGuid>e9ffbc07-4d8b-4150-82fb-1cff83d5112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Blouse')])[4]</value>
      <webElementGuid>33aeba76-4421-442e-b8c2-ff7c1b9b54d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$27.00'])[2]/following::a[1]</value>
      <webElementGuid>f837f8ec-b4e1-444f-8ce4-a3bc1ece653d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick view'])[1]/following::a[1]</value>
      <webElementGuid>9d993327-461e-4e89-adb9-f4e7e707f9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$27.00'])[3]/preceding::a[1]</value>
      <webElementGuid>b8e747aa-b848-460c-be61-297bc2e916b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::a[1]</value>
      <webElementGuid>2101feee-b0dd-486b-a2b3-96d4d96cf434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://automationpractice.com/index.php?id_product=2&amp;controller=product&amp;search_query=Blouse&amp;results=1'])[4]</value>
      <webElementGuid>a7b17e54-794d-4bfb-a2cb-1e43474e8732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h5/a</value>
      <webElementGuid>fcfee6f3-eb79-4304-9f50-5914d4af528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://automationpractice.com/index.php?id_product=2&amp;controller=product&amp;search_query=Blouse&amp;results=1' and @title = 'Blouse' and (text() = '
							Blouse
						' or . = '
							Blouse
						')]</value>
      <webElementGuid>a4ea9edd-e11a-4067-a4c2-a844fd334e61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
